"""Global error code constants for tool execution."""

# Generic tool/runtime
TOOL_UNKNOWN = "TOOL_UNKNOWN"
INVALID_CALL = "INVALID_CALL"
INVALID_ARGS = "INVALID_ARGS"
INVALID_RESULT_TYPE = "INVALID_RESULT_TYPE"
LIMIT_REACHED = "LIMIT_REACHED"
INTERRUPTED = "INTERRUPTED"
EXEC_FAILED = "EXEC_FAILED"

# Common operational categories
SANDBOX_BLOCKED = "SANDBOX_BLOCKED"
PERMISSION_DENIED = "PERMISSION_DENIED"
NOT_FOUND = "NOT_FOUND"
TIMEOUT = "TIMEOUT"
NETWORK_FAILED = "NETWORK_FAILED"
DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
BLOCKED_BY_USER = "BLOCKED_BY_USER"
